In [10]:
import numpy as np
import pandas as pd

Airbnb_data=pd.read_csv("Airbnb_Open_Data.csv")

C:\Users\darkw\AppData\Local\Temp\ipykernel_7280\2120126084.py:4: DtypeWarning: Columns (0: license) have mixed types. Specify dtype option on import or set low_memory=False.
  Airbnb_data=pd.read_csv("Airbnb_Open_Data.csv")

In [11]:
Airbnb_data.shape

(102599, 26)

In [12]:
Airbnb_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  str
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  str
 4   host name                       102193 non-null  str
 5   neighbourhood group             102570 non-null  str
 6   neighbourhood                   102583 non-null  str
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  str
 10  country code                    102468 non-null  str
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  str
 13  room type                       102599 non-null  str
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  str
 16  service fee                     102326 non-null  str
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   str
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   str
 25  license                         2 non-null       str
dtypes: float64(9), int64(2), object(1), str(14)
memory usage: 20.4+ MB

In [13]:
Airbnb_data.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

In [14]:
Airbnb_data.isnull().sum()

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                        52131
license                           102597
dtype: int64

In [15]:
Airbnb_data.head().T

,0,1,2,3,4
id,1001254,1002102,1002403,1002755,1003689
NAME,Clean & quiet apt home by the park,Skylit Midtown Castle,THE VILLAGE OF HARLEM....NEW YORK !,NaN,Entire Apt: Spacious Studio/Loft by central park
host id,80014485718,52335172823,78829239556,85098326012,92037596077
host_identity_verified,unconfirmed,verified,NaN,unconfirmed,verified
host name,Madaline,Jenna,Elise,Garry,Lyndon
neighbourhood group,Brooklyn,Manhattan,Manhattan,Brooklyn,Manhattan
neighbourhood,Kensington,Midtown,Harlem,Clinton Hill,East Harlem
lat,40.64749,40.75362,40.80902,40.68514,40.79851
long,-73.97237,-73.98377,-73.9419,-73.95976,-73.94399
country,United States,United States,United States,United States,United States
country code,US,US,US,US,US
instant_bookable,False,False,True,True,False
cancellation_policy,strict,moderate,flexible,moderate,moderate
room type,Private room,Entire home/apt,Private room,Entire home/apt,Entire home/apt
Construction year,2020.0,2007.0,2005.0,2005.0,2009.0
price,$966,$142,$620,$368,$204
service fee,$193,$28,$124,$74,$41
minimum nights,10.0,30.0,3.0,30.0,10.0
number of reviews,9.0,45.0,0.0,270.0,9.0
last review,10/19/2021,5/21/2022,NaN,7/5/2019,11/19/2018
reviews per month,0.21,0.38,NaN,4.64,0.1
review rate number,4.0,4.0,5.0,4.0,3.0
calculated host listings count,6.0,2.0,1.0,1.0,1.0
availability 365,286.0,228.0,352.0,322.0,289.0
house_rules,Clean up and treat the home the way you'd like...,Pet friendly but please confirm with me if the...,"I encourage you to use my kitchen, cooking and...",NaN,"Please no smoking in the house, porch or on th..."
license,NaN,NaN,NaN,NaN,NaN

### Problems Observed

1. There are inconsistent column names
2.

In [21]:
Airbnb_data.columns=(
    Airbnb_data.columns.str.strip()
    .str.lower()
    .str.replace(" ","_"))

In [23]:
Airbnb_data.columns

Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count',
       'availability_365', 'house_rules', 'license'],
      dtype='str')