#### Airbnb Open Data — Data Cleaning & Quality Analysis
## Project Overview
This project focuses on cleaning, validating, and preparing an Airbnb dataset for reliable data analysis.

The goal is to identify and resolve common data-quality problems such as:

1.Missing values

2.Duplicate records

3.Incorrect data types

4.Inconsistent column names

5.Invalid numerical values

6.Inconsistent categorical values

7.Incorrect date values

8.Formatting issues

9.Logical inconsistencies

10.Potential outliers

This project was completed as a practical data-cleaning exercise designed to simulate a real-world junior data scientist workflow.

Objective: Transform a raw, inconsistent dataset into a clean and analysis-ready dataset while documenting the reasoning behind each cleaning decision.

In [1]:
import numpy as np
import pandas as pd

Airbnb_data=pd.read_csv("Airbnb_Open_Data.csv")

C:\Users\darkw\AppData\Local\Temp\ipykernel_12928\2120126084.py:4: DtypeWarning: Columns (0: license) have mixed types. Specify dtype option on import or set low_memory=False.
  Airbnb_data=pd.read_csv("Airbnb_Open_Data.csv")

In [2]:
Airbnb_data.shape

(102599, 26)

In [3]:
Airbnb_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  str
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  str
 4   host name                       102193 non-null  str
 5   neighbourhood group             102570 non-null  str
 6   neighbourhood                   102583 non-null  str
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  str
 10  country code                    102468 non-null  str
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  str
 13  room type                       102599 non-null  str
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  str
 16  service fee                     102326 non-null  str
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   str
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   str
 25  license                         2 non-null       str
dtypes: float64(9), int64(2), object(1), str(14)
memory usage: 20.4+ MB

In [4]:
Airbnb_data.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

In [5]:
Airbnb_data[Airbnb_data.duplicated()]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
102058,35506831,Master Bedroom with private Bathroom & Balcony,55110690425,unconfirmed,UZeyir,Queens,Maspeth,40.74056,-73.90635,United States,...,$141,1.0,1.0,11/14/2021,0.27,3.0,1.0,339.0,NaN,NaN
102059,35507383,Cozy 2 br in sunny Fort Greene apt,80193772189,verified,Sally,Brooklyn,Fort Greene,40.68701,-73.97555,United States,...,$130,3.0,38.0,11/13/2021,0.27,3.0,1.0,0.0,NaN,NaN
102060,35507935,Duplex w/ Terrace @ Box House Hotel,72991962259,verified,The Box House Hotel,Brooklyn,Greenpoint,40.73756,-73.95350,United States,...,$181,3.0,10.0,11/13/2021,0.08,3.0,30.0,32.0,NaN,NaN
102061,35508488,"Cozy, clean Greenpoint room with yard access",74975156081,verified,Dawn,Brooklyn,Greenpoint,40.72516,-73.95004,United States,...,$118,30.0,38.0,11/13/2021,0.34,5.0,2.0,324.0,NaN,NaN
102062,35509040,2BR XL Loft: Cleaning CDC guidelines implemented,85844415221,unconfirmed,Vida,Brooklyn,Greenpoint,40.72732,-73.94185,United States,...,$71,30.0,13.0,11/13/2021,0.14,4.0,28.0,336.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [6]:
Airbnb_data.isnull().sum()

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                        52131
license                           102597
dtype: int64

In [7]:
Airbnb_data.head().T

,0,1,2,3,4
id,1001254,1002102,1002403,1002755,1003689
NAME,Clean & quiet apt home by the park,Skylit Midtown Castle,THE VILLAGE OF HARLEM....NEW YORK !,NaN,Entire Apt: Spacious Studio/Loft by central park
host id,80014485718,52335172823,78829239556,85098326012,92037596077
host_identity_verified,unconfirmed,verified,NaN,unconfirmed,verified
host name,Madaline,Jenna,Elise,Garry,Lyndon
neighbourhood group,Brooklyn,Manhattan,Manhattan,Brooklyn,Manhattan
neighbourhood,Kensington,Midtown,Harlem,Clinton Hill,East Harlem
lat,40.64749,40.75362,40.80902,40.68514,40.79851
long,-73.97237,-73.98377,-73.9419,-73.95976,-73.94399
country,United States,United States,United States,United States,United States
country code,US,US,US,US,US
instant_bookable,False,False,True,True,False
cancellation_policy,strict,moderate,flexible,moderate,moderate
room type,Private room,Entire home/apt,Private room,Entire home/apt,Entire home/apt
Construction year,2020.0,2007.0,2005.0,2005.0,2009.0
price,$966,$142,$620,$368,$204
service fee,$193,$28,$124,$74,$41
minimum nights,10.0,30.0,3.0,30.0,10.0
number of reviews,9.0,45.0,0.0,270.0,9.0
last review,10/19/2021,5/21/2022,NaN,7/5/2019,11/19/2018
reviews per month,0.21,0.38,NaN,4.64,0.1
review rate number,4.0,4.0,5.0,4.0,3.0
calculated host listings count,6.0,2.0,1.0,1.0,1.0
availability 365,286.0,228.0,352.0,322.0,289.0
house_rules,Clean up and treat the home the way you'd like...,Pet friendly but please confirm with me if the...,"I encourage you to use my kitchen, cooking and...",NaN,"Please no smoking in the house, porch or on th..."
license,NaN,NaN,NaN,NaN,NaN

### DATA CLEANING

In [8]:
Airbnb_data_clean=Airbnb_data.copy()

In [9]:
Airbnb_data_clean.columns=(
    Airbnb_data_clean.columns.str.strip().str.lower().str.replace(" ","_")
)
Airbnb_data_clean.columns

Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count',
       'availability_365', 'house_rules', 'license'],
      dtype='str')

In [10]:
Airbnb_data_clean.isnull().sum()

id                                     0
name                                 250
host_id                                0
host_identity_verified               289
host_name                            406
neighbourhood_group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country_code                         131
instant_bookable                     105
cancellation_policy                   76
room_type                              0
construction_year                    214
price                                247
service_fee                          273
minimum_nights                       409
number_of_reviews                    183
last_review                        15893
reviews_per_month                  15879
review_rate_number                   326
calculated_host_listings_count       319
availability_365                     448
house_rules                        52131
license                           102597
dtype: int64

In [11]:
Airbnb_data_clean.columns

Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count',
       'availability_365', 'house_rules', 'license'],
      dtype='str')

In [12]:
Airbnb_data_clean['instant_bookable']=Airbnb_data_clean['instant_bookable'].astype(bool)
Airbnb_data_clean['last_review']=pd.to_datetime(Airbnb_data_clean['last_review'])

#Checking to see whether the following attributes have off data values
cols=['calculated_host_listings_count','review_rate_number','minimum_nights', 'construction_year','availability_365','number_of_reviews']
for col in cols:
    print(f"\n======{col}=======")
    print(Airbnb_data_clean[col].unique())

======calculated_host_listings_count=======
[  6.   2.   1.   4.   3.  nan   5.   7.  13.  28.  11.   8.   9.  52.
  18.  15.  19.  10.  39.  26.  29.  12.  21.  96.  14.  34.  43. 121.
  37.  49.  31.  91.  16.  87.  33.  23.  50.  20.  25. 232.  17.  47.
 103.  65.  30.  27. 327.  32.  45.  53. 208. 171.  44.  48. 108.  51.
 161. 152.  83.  24.  22. 126.  54.  66.  59.  62. 102. 186. 125.  55.
  63.  67.  58.  56.  80.  46. 218.  86. 332.]

======review_rate_number=======
[ 4.  5.  3. nan  2.  1.]

======minimum_nights=======
[ 1.000e+01  3.000e+01  3.000e+00  4.500e+01  2.000e+00  1.000e+00
  5.000e+00  4.000e+00  9.000e+01  7.000e+00  1.400e+01  6.000e+01
        nan  1.800e+02  9.000e+00  3.100e+01  6.000e+00  1.500e+01
  2.900e+01  8.000e+00  4.700e+01  8.100e+01  1.440e+02  3.710e+02
  1.490e+02  2.730e+02  1.310e+02  2.750e+02  3.230e+02  5.900e+01
  9.900e+01  2.680e+02 -1.000e+01  1.890e+02  3.400e+02  1.280e+02
  3.500e+02  1.660e+02  1.100e+02  5.700e+01  1.420e+02  3.660e+02
  2.800e+01  2.000e+02  5.000e+01  3.990e+02  1.700e+01  1.100e+01
  4.520e+02  2.500e+01  1.300e+01  3.455e+03 -5.000e+00  2.100e+01
  2.700e+01  1.800e+01  3.650e+02 -1.000e+00  2.000e+01 -1.200e+01
  4.000e+01  4.400e+01  3.980e+02 -2.000e+00  6.500e+01 -3.000e+00
  5.500e+01  1.200e+02  1.220e+02  1.900e+01  2.400e+02  8.800e+01
  1.150e+02  1.500e+02  3.700e+02  1.600e+01  8.000e+01  1.810e+02
  2.600e+01  2.650e+02  3.000e+02  1.850e+02  3.600e+02  5.600e+01
  1.200e+01  7.000e+01  3.900e+01  2.400e+01  3.200e+01  1.000e+03
  2.700e+02  2.200e+01  7.500e+01  2.500e+02  6.200e+01  2.300e+01
  1.250e+03  3.640e+02  7.400e+01  1.980e+02  1.000e+02  5.000e+02
  4.300e+01  3.500e+01  9.100e+01  4.800e+02  5.300e+01  1.600e+02
  9.990e+02  1.860e+02  6.800e+01  9.300e+01  8.700e+01  1.830e+02
  2.990e+02  1.750e+02  9.800e+01  1.330e+02  3.540e+02  4.200e+01
  3.300e+01  3.700e+01  2.250e+02  4.000e+02  1.050e+02  1.840e+02
  1.530e+02  1.340e+02  2.220e+02  5.800e+01  2.100e+02  1.820e+02
  9.540e+02  5.645e+03  2.645e+03 -1.223e+03 -3.650e+02 -2.000e+02
  1.140e+02  8.500e+01  3.600e+01  4.800e+01  1.550e+02  3.070e+02
  1.290e+02  1.450e+02  6.400e+01  3.330e+02  1.190e+02 -1.250e+02
  1.250e+02  3.400e+01  4.580e+02  8.250e+02]

======construction_year=======
[2020. 2007. 2005. 2009. 2013. 2015. 2004. 2008. 2010. 2019. 2018. 2006.
 2016. 2017. 2021. 2003. 2011. 2012. 2022. 2014.   nan]

======availability_365=======
[ 2.860e+02  2.280e+02  3.520e+02  3.220e+02  2.890e+02  3.740e+02
  2.240e+02  2.190e+02  1.800e+02  3.750e+02  1.000e+00  1.630e+02
  2.580e+02  4.700e+01  6.800e+01  1.000e+02  1.970e+02  9.600e+01
  3.250e+02  3.450e+02  3.470e+02  1.930e+02  5.400e+01  9.000e+00
  3.440e+02  3.720e+02  1.030e+02  1.720e+02  5.600e+01  1.050e+02
  1.690e+02  3.830e+02  4.110e+02  7.600e+01  4.160e+02  2.940e+02
  2.140e+02  3.560e+02  1.100e+02  3.540e+02  3.300e+01  4.050e+02
  8.600e+01  1.520e+02  3.530e+02  2.600e+01  3.200e+01  8.500e+01
        nan  8.200e+01  9.200e+01  5.500e+01  1.580e+02  6.400e+01
  1.840e+02  2.010e+02  3.280e+02  3.930e+02  6.100e+01  2.670e+02
  1.890e+02  8.300e+01  4.000e+02  3.400e+01  2.030e+02  3.500e+01
  2.800e+02  4.170e+02  1.620e+02  2.370e+02  2.420e+02  2.270e+02
  1.730e+02  1.460e+02  2.430e+02  4.250e+02  1.130e+02  2.600e+02
  3.950e+02  2.660e+02  5.800e+01  4.100e+02  3.880e+02  1.300e+01
  6.200e+01  3.660e+02  3.380e+02  3.340e+02 -1.000e+01  3.780e+02
 -2.000e+00  3.510e+02  3.890e+02  1.600e+01  3.370e+02  1.660e+02
  1.800e+01  1.300e+02  4.300e+01  0.000e+00  3.730e+02  4.260e+02
  3.960e+02  4.190e+02  3.770e+02  1.900e+02  3.350e+02  5.200e+01
  7.000e+01  3.110e+02  1.410e+02 -1.000e+00  2.630e+02  2.000e+02
  1.440e+02  3.200e+02  1.900e+01  2.930e+02  2.400e+02  3.000e+02
  4.210e+02  3.320e+02  2.710e+02  1.560e+02  4.200e+02  3.990e+02
  1.200e+01  1.500e+01  1.380e+02  3.270e+02  1.240e+02  1.370e+02
  1.920e+02  8.100e+01  3.610e+02  3.410e+02  2.130e+02  3.360e+02
  2.300e+01  7.800e+01  1.880e+02  6.600e+01  8.000e+01  3.820e+02
  3.290e+02  2.560e+02 -6.000e+00  3.860e+02  1.090e+02  3.190e+02
  5.000e+01  1.180e+02  3.500e+02  1.500e+02  3.130e+02  2.480e+02
  2.300e+02  1.450e+02  4.070e+02  4.220e+02  4.600e+01  1.010e+02
  2.100e+02  1.040e+02  3.230e+02  2.060e+02  2.950e+02  3.970e+02
  2.760e+02  3.980e+02  1.350e+02  4.120e+02  8.700e+01 -9.000e+00
  3.150e+02  1.320e+02  4.200e+01  7.300e+01  1.770e+02  2.450e+02
  2.720e+02  2.470e+02  3.940e+02  1.790e+02  3.100e+01  9.500e+01
  1.540e+02  2.040e+02  3.710e+02  3.120e+02  3.800e+02  2.700e+02
  4.500e+01  1.760e+02  3.790e+02  2.640e+02  4.020e+02  5.300e+01
  2.520e+02  5.000e+00  3.620e+02  2.380e+02  4.140e+02  2.090e+02
  4.060e+02  1.100e+01  2.350e+02  3.180e+02  1.400e+02  1.070e+02
  1.310e+02  1.170e+02  3.160e+02  1.190e+02  4.240e+02  1.550e+02
  2.870e+02  8.400e+01  2.910e+02  2.070e+02  3.490e+02  1.980e+02
  1.430e+02  2.850e+02  3.580e+02  3.310e+02  2.830e+02  1.140e+02
  7.700e+01  3.760e+02  2.110e+02  1.120e+02  2.960e+02  1.810e+02
  1.060e+02  9.700e+01  3.680e+02  2.310e+02  2.970e+02 -4.000e+00
  1.990e+02  1.000e+01  9.400e+01  7.500e+01  1.820e+02  1.640e+02
  3.810e+02  2.530e+02  1.910e+02  7.100e+01  9.800e+01  4.080e+02
  1.590e+02  3.260e+02  1.470e+02  1.860e+02  1.870e+02  2.680e+02
  8.800e+01  4.040e+02  3.690e+02  2.920e+02  1.710e+02  3.010e+02
  1.290e+02  3.000e+01  3.650e+02  2.690e+02  6.700e+01  3.400e+02
  6.300e+01  2.360e+02 -8.000e+00  2.510e+02  3.240e+02  9.300e+01
  9.100e+01  2.590e+02  4.000e+00  3.840e+02  2.650e+02  2.210e+02
  1.220e+02  7.000e+00  2.900e+01  1.160e+02  3.920e+02  1.750e+02
  3.030e+02  2.330e+02  6.900e+01  3.670e+02  2.390e+02  3.600e+01
  1.490e+02  3.900e+01  3.870e+02  3.210e+02  3.020e+02  3.000e+00
  1.830e+02  8.000e+00  2.440e+02  6.000e+01  1.530e+02  3.550e+02
  2.500e+02  3.640e+02 -5.000e+00  2.160e+02  4.180e+02  1.670e+02
  1.780e+02  1.400e+01  3.700e+02  2.540e+02  2.200e+01  3.330e+02
  2.400e+01  2.460e+02  2.610e+02  1.420e+02  2.120e+02  3.390e+02
  2.800e+01  3.090e+02  1.740e+02  2.320e+02  2.000e+01  1.330e+02
  1.700e+01  2.700e+01  4.100e+01  2.260e+02  1.080e+02  1.680e+02
  2.550e+02  2.780e+02  1.250e+02  5.700e+01  1.390e+02  6.500e+01
  2.250e+02  2.050e+02  2.810e+02  2.500e+01  1.950e+02  3.700e+01
  2.790e+02  1.150e+02  2.740e+02  2.150e+02  1.340e+02  6.000e+00
  1.940e+02  1.110e+02  2.170e+02  1.960e+02  2.200e+02  2.180e+02
  4.230e+02  3.300e+02  7.900e+01  1.850e+02  9.000e+01  2.000e+00
  2.750e+02  3.480e+02  3.140e+02  3.100e+02  1.600e+02  3.570e+02
  4.400e+01  3.590e+02  2.990e+02  4.130e+02  2.820e+02  2.900e+02
  1.260e+02  3.800e+01  2.490e+02  2.020e+02  7.200e+01  2.770e+02
  2.100e+01  1.650e+02  7.400e+01  2.220e+02  4.090e+02  1.700e+02
  2.410e+02  8.900e+01  1.280e+02  1.210e+02  2.230e+02  2.730e+02
  5.900e+01  1.230e+02  2.290e+02 -3.000e+00  3.850e+02  3.050e+02
  3.070e+02  9.900e+01  2.340e+02  2.570e+02  3.060e+02  5.100e+01
  2.080e+02  2.840e+02  1.360e+02  3.910e+02  4.900e+01  1.510e+02
  1.270e+02  3.430e+02  3.080e+02  1.480e+02  4.010e+02  3.170e+02
  3.040e+02  1.610e+02  3.600e+02  2.980e+02  4.000e+01  3.630e+02
  4.030e+02  1.570e+02  3.420e+02  2.620e+02  3.900e+02  3.460e+02
  1.020e+02  4.800e+01  1.200e+02  2.880e+02 -7.000e+00  4.150e+02
  3.677e+03]

======number_of_reviews=======
[9.000e+00 4.500e+01 0.000e+00 2.700e+02 7.400e+01 4.900e+01 4.300e+02
 1.180e+02 1.600e+02 5.300e+01 1.880e+02 1.670e+02 1.130e+02 2.700e+01
 1.480e+02 1.980e+02 2.600e+02 1.300e+02 3.900e+01 7.100e+01 8.800e+01
 1.900e+01 5.800e+01 1.080e+02 2.900e+01 2.420e+02 1.970e+02 2.730e+02
 1.680e+02 2.310e+02 2.140e+02 2.450e+02 1.500e+01 2.500e+01 8.100e+01
 9.700e+01 1.100e+01 2.480e+02 6.100e+01 1.350e+02 1.120e+02 7.300e+01
 8.200e+01 3.280e+02 1.050e+02 2.890e+02 1.380e+02 2.100e+01 4.200e+01
 5.000e+00 6.600e+01 1.430e+02 1.910e+02 4.000e+00 3.380e+02 1.060e+02
 1.900e+02 2.300e+01 1.420e+02 5.400e+01 7.000e+01 1.600e+01 9.400e+01
 1.940e+02 2.000e+00 1.740e+02 2.400e+01 1.660e+02       nan 1.000e+00
 3.000e+01 1.390e+02 2.330e+02 6.800e+01 4.600e+01 3.350e+02 1.620e+02
 1.700e+02 3.340e+02 1.200e+01 4.670e+02 7.000e+00 3.800e+01 3.240e+02
 1.150e+02 3.540e+02 1.950e+02 1.300e+01 3.600e+01 6.300e+01 1.550e+02
 1.930e+02 3.200e+01 5.000e+01 2.600e+01 4.260e+02 2.270e+02 8.400e+01
 1.000e+01 1.240e+02 2.400e+02 2.000e+02 7.900e+01 3.400e+01 1.340e+02
 1.260e+02 2.340e+02 2.020e+02 2.800e+01 3.090e+02 1.400e+01 8.000e+01
 2.940e+02 1.500e+02 4.700e+01 2.190e+02 1.140e+02 2.130e+02 8.600e+01
 1.800e+01 2.060e+02 1.220e+02 3.300e+01 5.200e+01 5.100e+01 1.990e+02
 3.000e+00 4.100e+01 1.090e+02 1.510e+02 2.850e+02 3.750e+02 6.000e+00
 3.580e+02 2.260e+02 1.040e+02 2.040e+02 2.530e+02 1.290e+02 3.700e+01
 6.900e+01 1.920e+02 1.700e+01 2.220e+02 2.050e+02 4.580e+02 1.830e+02
 1.890e+02 1.270e+02 3.500e+01 1.710e+02 9.200e+01 2.380e+02 5.600e+01
 1.110e+02 1.470e+02 1.770e+02 1.850e+02 6.200e+01 1.810e+02 3.330e+02
 4.410e+02 2.790e+02 2.030e+02 2.100e+02 6.400e+01 1.320e+02 2.000e+01
 6.700e+01 1.870e+02 2.200e+01 9.300e+01 4.800e+01 1.200e+02 4.300e+01
 5.900e+01 3.100e+01 2.200e+02 2.860e+02 3.980e+02 7.600e+01 1.820e+02
 8.000e+00 2.280e+02 3.880e+02 2.230e+02 2.180e+02 7.500e+01 3.700e+02
 1.310e+02 1.360e+02 9.800e+01 3.800e+02 1.630e+02 2.470e+02 1.160e+02
 3.200e+02 2.250e+02 9.500e+01 4.030e+02 1.750e+02 2.630e+02 2.320e+02
 7.200e+01 4.140e+02 1.190e+02 1.170e+02 3.850e+02 1.030e+02 2.800e+02
 5.700e+01 4.800e+02 1.010e+02 8.700e+01 2.410e+02 9.000e+01 9.900e+01
 2.710e+02 8.900e+01 1.790e+02 4.010e+02 8.300e+01 2.110e+02 2.950e+02
 2.070e+02 1.720e+02 3.300e+02 1.230e+02 5.500e+01 2.580e+02 1.280e+02
 1.520e+02 1.540e+02 1.640e+02 2.780e+02 2.350e+02 3.050e+02 1.020e+02
 6.500e+01 4.000e+01 1.000e+02 1.250e+02 2.290e+02 6.000e+01 1.070e+02
 1.760e+02 1.780e+02 2.160e+02 3.140e+02 1.530e+02 1.100e+02 2.440e+02
 2.080e+02 1.210e+02 1.570e+02 2.090e+02 4.400e+01 1.580e+02 2.360e+02
 2.150e+02 7.800e+01 2.970e+02 7.700e+01 2.650e+02 1.560e+02 2.720e+02
 2.680e+02 1.330e+02 1.650e+02 2.690e+02 2.430e+02 1.370e+02 1.450e+02
 3.390e+02 4.540e+02 2.300e+02 1.440e+02 4.390e+02 2.610e+02 3.190e+02
 1.840e+02 4.510e+02 1.690e+02 2.660e+02 2.510e+02 1.410e+02 3.040e+02
 4.740e+02 8.500e+01 2.210e+02 2.010e+02 3.210e+02 2.500e+02 1.490e+02
 2.540e+02 1.610e+02 3.230e+02 3.470e+02 2.960e+02 9.600e+01 1.730e+02
 2.390e+02 4.040e+02 3.260e+02 3.630e+02 1.460e+02 3.270e+02 2.370e+02
 3.530e+02 9.100e+01 3.020e+02 2.760e+02 1.860e+02 3.220e+02 2.670e+02
 5.400e+02 2.240e+02 2.910e+02 3.150e+02 3.130e+02 5.940e+02 5.970e+02
 6.070e+02 2.870e+02 1.590e+02 3.950e+02 4.470e+02 2.810e+02 3.560e+02
 3.600e+02 3.490e+02 2.460e+02 3.080e+02 2.920e+02 1.400e+02 2.840e+02
 3.740e+02 1.960e+02 2.120e+02 2.740e+02 3.400e+02 3.860e+02 3.360e+02
 2.490e+02 2.750e+02 2.590e+02 2.520e+02 2.980e+02 2.880e+02 2.550e+02
 3.650e+02 2.570e+02 2.170e+02 4.880e+02 3.320e+02 1.800e+02 2.770e+02
 3.890e+02 3.720e+02 2.990e+02 3.940e+02 3.570e+02 3.500e+02 3.520e+02
 3.510e+02 2.620e+02 3.180e+02 3.070e+02 3.250e+02 2.820e+02 3.960e+02
 4.660e+02 3.970e+02 2.900e+02 4.480e+02 4.240e+02 4.080e+02 5.430e+02
 2.640e+02 6.290e+02 5.760e+02 2.560e+02 4.590e+02 4.120e+02 3.780e+02
 4.110e+02 4.340e+02 5.100e+02 3.060e+02 3.920e+02 4.170e+02 3.680e+02
 4.360e+02 3.100e+02 3.410e+02 3.480e+02 7.760e+02 8.490e+02 6.180e+02
 4.850e+02 5.500e+02 3.640e+02 4.150e+02 4.430e+02 3.770e+02 3.790e+02
 3.290e+02 4.750e+02 9.660e+02 7.970e+02 5.920e+02 5.670e+02 6.480e+02
 3.670e+02 4.830e+02 3.460e+02 4.060e+02 4.690e+02 3.420e+02 3.110e+02
 3.450e+02 6.380e+02 3.620e+02 5.600e+02 6.980e+02 3.990e+02 4.320e+02
 3.440e+02 4.490e+02 5.420e+02 3.710e+02 2.930e+02 3.610e+02 4.700e+02
 4.730e+02 3.870e+02 4.960e+02 4.380e+02 4.130e+02 1.024e+03 3.010e+02
 3.030e+02 4.550e+02 8.840e+02 4.180e+02 5.200e+02 5.660e+02 2.830e+02
 4.400e+02 3.120e+02 4.200e+02 4.330e+02 3.370e+02 4.500e+02 5.830e+02
 3.160e+02 4.910e+02 3.660e+02 3.430e+02 6.790e+02 5.630e+02 3.170e+02
 3.730e+02 5.560e+02 4.290e+02 3.310e+02 4.680e+02 7.380e+02 4.770e+02
 4.840e+02 5.010e+02 4.210e+02 1.010e+03 4.460e+02 4.900e+02 4.000e+02
 3.000e+02]

In [17]:
for col in cols:
    Airbnb_data_clean[col]=Airbnb_data_clean[col].astype("Int64")

In [14]:

cols=['price','service_fee']
for col in cols:
    Airbnb_data_clean[col]=Airbnb_data_clean[col].replace(r"[$]"," ", regex=True).replace(r"[\,]","", regex=True)
    Airbnb_data_clean[col]=Airbnb_data_clean[col].astype("Int64")

In [15]:

missing_values=Airbnb_data_clean.isnull().mean()*100
print(missing_values[missing_values>0].sort_values(ascending=False))

license                           99.998051
house_rules                       50.810437
last_review                       15.490404
reviews_per_month                 15.476759
country                            0.518524
availability_365                   0.436651
minimum_nights                     0.398639
host_name                          0.395715
review_rate_number                 0.317742
calculated_host_listings_count     0.310919
host_identity_verified             0.281679
service_fee                        0.266084
name                               0.243667
price                              0.240743
construction_year                  0.208579
number_of_reviews                  0.178364
country_code                       0.127682
cancellation_policy                0.074075
neighbourhood_group                0.028265
neighbourhood                      0.015595
lat                                0.007797
long                               0.007797
dtype: float64

In [16]:
Airbnb_data_clean=Airbnb_data_clean.drop(['license'], axis=1)

### Future Improvements
#### After completing the cleaning stage, this project can be extended into a full exploratory data-analysis project.

Potential next steps include:

Analyze Airbnb pricing patterns

Explore neighbourhood differences

Investigate room-type distributions

Analyze reviews and ratings

Examine availability patterns

Explore relationships between price and reviews

Visualize geographical patterns

Identify factors associated with listing prices

Build a predictive model for Airbnb prices

#### Author
#### Solomon Ayensu

BSc Information Technology Student
Ghana Communication Technology University

Areas of Interest
Data Science

Data Analysis

Python

Machine Learning

Software Engineering

📬 Contact
If you have feedback or suggestions regarding this project, feel free to connect with me through GitHub or LinkedIn.